name: ublue-38
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '0 15 * * *'  # 3pm UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  build-38:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 38