name: ublue main 38
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '15 15 * * *'  # 3pm-ish UTC everyday (timed against official fedora container pushes)
  workflow_dispatch:

jobs:
  ublue-38:
    name: "build ublue-os/*-main:38"
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: 38